### ISSUE TITLE
Incorrect usage Promise interface with new React

### ISSUE THREAD

**Issue by DangerLifter** [clue/php-redis-react#27]
On trying use: subscribe functionality or (eg. examples/monitor.php)

PHP Fatal error:  Call to undefined method React\Promise\Deferred::then() in /var/www/projects/DomainScrapper/vendor/clue/redis-react/src/StreamingClient.php on line 105

**Comment by clue** [comment]
Thanks for reporting! I can reproduce this locally and will look into this shortly.

**Comment by clue** [comment]
Just released a v0.5.1 tag that includes this bugfix. Thanks!
