### ISSUE TITLE
Fix documentation for on pmessage.

### ISSUE THREAD

**Issue by rquast** [clue/php-redis-react#33]
The docs has this for on pmessage..
```
$client->on('pmessage', function ($pattern, $payload) {
}
```

It should be this ...
```
$client->on('pmessage', function ($pattern, $channel, $payload) {
}
```

Where $channel is the channel it matches.

**Comment by clue** [comment]
Thanks for the find @rquast!

Can you file a PR to fix this documentation issue? :)
