### ISSUE TITLE
Can't Pub/Sub On Same Client

### ISSUE THREAD

**Issue by daneren2005** [clue/php-redis-react#39]
It appears that pub sub is not really async.  After trying to figure out why I wasn't receiving commands on another client, I finally tried commenting out `$client->subscribe($channel);` and all of a sudden the publish commands were going through.

With a client subscribe the following code never logged the publish complete message:
```
$this->redis->publish($this->channel, json_encode($msg))->then(function($return) {
	$this->debug('Publish received ' . $return);
});
```

**Comment by clue** [comment]
This is a limitation of Redis and unfortunately there's nothing this library (or any other library for that matter) can do about this. See also http://redis.io/topics/pubsub and http://redis.io/commands/subscribe.

You can easily reproduce this by connecting to your Redis instance via telnet:

```php
$ telnet localhost 6379
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
subscribe a
*3
$9
subscribe
$1
a
:1
publish a b
-ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```

As you've already figured out, the correct workaround is to use two independent connections.

I hope this helps :+1:

**Comment by daneren2005** [comment]
Oh well that stinks.  I was hoping because it async it meant you could listen for replies to the subscribe and publish on the same channel.  That does make sense that it is a Redis thing which you can't work around.
