### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#43]
How can I set command options?
for example for ```SET``` command according to https://redis.io/commands/set we have these options

* EX seconds -- Set the specified expire time, in seconds.
* PX milliseconds -- Set the specified expire time, in milliseconds.
* NX -- Only set the key if it does not already exist.
* XX -- Only set the key if it already exist.

**Comment by clue** [comment]
Technically, these are not options but actually additional command arguments. In other words, you can simply pass these like this:

```php
$client->set('hello', 'world', 'PX', 500);
```

I hope this helps :+1:

**Comment by sm2017** [comment]
Thanks a lot
