### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#45]
I use the following code

```php
$client->HMSET('test','a'=>'z','b'=>null);
```

But when I use the following code
```php
$client->HGETALL('test');
```

field ```b``` is empty string not null , How can I get it as null? without serialize , json and ...

**Comment by sm2017** [comment]
Reply please

**Comment by clue** [comment]
Your first snippet contains a syntax error, so I'm not sure what's supposed to happen anyway :-)

This library provides a very thin layer around Redis commands and follows its exact command semantics. If you check https://redis.io/commands/hmset, you'll see that it expects a variable number of strings. If you pass any other value, it will implicitly be converted to string, hence you're seeing an empty string for your `null` value.

If you want to store any other value, you'll have to serialize your values to strings, for example through `json_encode()` or `serialize()`.

I hope this helps :+1:
