### ISSUE TITLE
Race condition when submitting multiple commands

### ISSUE THREAD

**Issue by pwhelan** [clue/php-redis-react#54]
I frequently see promises being resolved with results that incorrect format, ie:

  * HGETALL resolves with a string.
  * HGETALL resolves with an array but with the wrong fields
  * GET resolves with an array.
  * etc..

I cannot confirm but I believe the problem is a race that occurs when a command is being submitted and a response is already queued up on the socket or is queued up before the write resolves but before it finishes. I'm still not clear on this, but I have seen the problem enough times to know it is real.

I will submit an actual test as soon as I can, hopefully with a PR as well.

**Comment by clue** [comment]
Thanks for reporting! I'm currently not aware of any such issue and don't see any code that would cause such a "race condition". Does this happen regularly? Can you provide a gist to reproduce this?

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:
