### ISSUE TITLE
use `redis-react` to subscribe message，how to reconnect

### ISSUE THREAD

**Issue by BelieveCode** [clue/php-redis-react#55]
my code is below 

    $factory->createClient("{$redisHost}:{$redisPort}")->then(function (Client $client) {
        $client->subscribe('device_change')->then(function () {
            echo 'Now subscribed to channel ' . PHP_EOL;
        });

        $client->on('message', function ($channel, $message) {
            echoln("get message"));
        });

        $client->on('close', function () {
            echoln('close');

            //set a Timer to reconnect the connect
            $timer_id = Timer::add(5, function () use (&$timer_id) {
                // todo ,here how to reconnect
                // 

            });

        });
        $client->on('error', function (Exception $e) {
            echoln('error' . $e->getMessage());
        });
    });

**Comment by BelieveCode** [comment]
processes management use  Workerman-3.5.0

**Comment by clue** [comment]
Hi! The basic idea is to assign your connection function to a variable and then pass this connection function to the close handler similar to this:

```php
$connect = $factory->createClient("{$redisHost}:{$redisPort}")->then(function (Client $client) use (&$connect) {
    $client->subscribe('device_change')->then(function () {
        echo 'Now subscribed to channel ' . PHP_EOL;
    });

    $client->on('message', function ($channel, $message) {
        echoln("get message"));
    });

    $client->on('close', function () use ($connect) {
        echoln('close');

        //set a Timer to reconnect the connect
        $timer_id = Timer::add(5, function () use (&$timer_id, $connect) {
            $connect();
        });

    });
    $client->on('error', function (Exception $e) {
        echoln('error' . $e->getMessage());
    });
});
```

I hope this helps :+1:

**Comment by BelieveCode** [comment]
Thank you, I get it, I will try.

maybe you can add Retry Policies like Workerman. [http://doc3.workerman.net/worker-development/reconnect.html](url)

    use \Workerman\Worker;
    use \Workerman\Connection\AsyncTcpConnection;
    require_once __DIR__ . '/Workerman/Autoloader.php';

    $worker = new Worker();

    $worker->onWorkerStart = function($worker)
    {
        $con = new AsyncTcpConnection('ws://echo.websocket.org:80');
        $con->onConnect = function($con) {
            $con->send('hello');
        };
        $con->onMessage = function($con, $msg) {
            echo "recv $msg\n";
        };
        $con->onClose = function($con) {
            // 如果连接断开，则在1秒后重连
            $con->reConnect(1);
        };
        $con->connect();
    };

    Worker::runAll();

**Comment by clue** [comment]
Makes perfect sense! There are currently no immediate plans to build this from my end (no demand at the moment), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

**Comment by BelieveCode** [comment]
OK, TRY.
