### ISSUE TITLE
Client interface methods

### ISSUE THREAD

**Issue by nusje2000** [clue/php-redis-react#67]
I've been working with react php for a few weeks now and since today I'm trying out this package. So far it seems to work fine but I'm missing a few methods inside the Client interface, such as: `subscribe`, `publish`, `get` and `set`. I don't know if this was intentional but I would like to see it sometime in the future.

**Comment by clue** [comment]
Welcome to @ReactPHP :-)

The `Client` uses the magic `__call()` method, see also the [README](https://github.com/clue/php-redis-react#commands):
> Listing all available commands is out of scope here, please refer to the Redis command reference. All Redis commands are automatically available as public methods via the magic __call() method.

I hope this helps! :+1:

**Comment by nusje2000** [comment]
Ahh, fast awnser btw :O, I noticed it because my IDE was crying about it. thanks for the help ;).
