### ISSUE TITLE
Expire bug

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#71]
I have a use case that only use `SET` and `GET` commands in redis , Always I use `EX` option in `SET` command

```
SET mykey "Hello" EX 10
GET mykey
```

I see that some keys in redis has TTL = -1 , and `GET mykey` returns value of key

I think there is a bug in `clue/php-redis-react` that don't send additional option to redis sometimes

From https://redis.io/commands/expire I know that
>The timeout will only be cleared by commands that delete or overwrite the contents of the key

But as I told before I just __overwrite the contents of the key__ by `SET` and always use `EX` option so all keys must be expired

In PHP script I use the following command to `SET` a value to a key

```php
$client->set('mykey', 'Hello','EX',10);
```

**Comment by clue** [comment]
The commands you've described here LGTM, so I'm not seeing any obvious problems. The way these commands are executed should ensure that all keys expire in 10s each.

This library merely forwards all commands/arguments to your Redis server as-is, so I don't see anything that could cause a bug here.

If "some keys" are not affected by this, I would suggest checking for other places that access the same database, for example by using the MONITOR command to see if anybody messes with your data.

I hope this helps 👍
