### ISSUE TITLE
Question : Async transaction

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#72]
Is `clue/php-redis-react` safe for redis transactions?

```php
$client->multi();
$client->incr('foo');
$client->incr('bar');
$client->exec();
```

I want to know as  `clue/php-redis-react` have async behavior . Do you handle transaction correctly?

**Comment by clue** [comment]
Yes, this is correctly handled by this library. Redis is responsible for transaction handling, this library merely transports your commands/arguments to your Redis server.

The [`EXEC` command](https://redis.io/commands/exec) will return with an array of replies for all commands in your transaction.
