### ISSUE TITLE
How to stop the loop without closing the connections

### ISSUE THREAD

**Issue by halaei** [clue/php-redis-react#76]
Is there any way to stop the react event loop and keeping the redis connection open? I just want to use this package to send a command to multiple instances of redis at once and wait for all the responses inside a laravel application. I don't think it is a good idea to add extra overhead to reconnect everytime I need to do that.

**Comment by clue** [comment]
This is currently not supported. Redis is usually assumed to run on the same box (or very close to it), so creating a new TCP/IP actuall has very little overhead).

Keeping the connection open would also involve some kind of connection state in order to not mess up the messages that get sent over it. ReactPHP is designed to keep running in the background, so this allows you to keep a connection open for any period of time you want without ever having to reconnect.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by halaei** [comment]
Thanks for the quick reply.
I will appreciate your help if you can give me a hint on anyway to send async requests to redis without using some infinite event looping.
The model I have in mind is something like guzzlehttp async request handling. No event loop is involved there. I just send multiple requests then call wait(). All the open connections will remain open for the future use:
```php
$client = new Client(['base_uri' => 'http://httpbin.org/']);
// Initiate each request but do not block
$promises = [
    'image' => $client->getAsync('/image'),
    'png'   => $client->getAsync('/image/png'),
    'jpeg'  => $client->getAsync('/image/jpeg'),
    'webp'  => $client->getAsync('/image/webp')
];
// Wait for the requests to complete, even if some of them fail
$results = Promise\settle($promises)->wait();
```
In my use-case, I will probably have my redis instances outside my main server, so the impact of reconnecting on performance will probably be greater than usual.

**Comment by clue** [comment]
It sounds like you may want to give https://github.com/clue/php-block-react a try? :-)

This allows you to "await" (keep the loop running) a certain number of promises.

**Comment by halaei** [comment]
@clue That seems awesome. I came up with this sample code:
```php
function executeCommandOnAllClients($loop, $clients, \Closure $command) {
    /** @var \React\Promise\Promise[] $promises */
    $promises = [];
    foreach ($clients as $client) {
        $promises[] = $client->then($command);
    }

    Clue\React\Block\awaitAll($promises, $loop);

    $results = [];
    $errors = [];
    foreach ($promises as $i => $promise) {
        $promise->done(function ($r) use ($i, &$results) {
            $results[$i] = $r;
        }, function ($e) use ($i, &$errors) {
            $errors[$i] = $e;
        });
    }

    return [
        'fulfilled' => $results,
        'rejected' => $errors,
    ];
}

function testExecuteCommandOnAllClients() {
    $loop = React\EventLoop\Factory::create();
    $factory = new \Clue\React\Redis\Factory($loop);
    $clients = [
        $client1 = $factory->createClient('localhost:6379'),
        $client2 = $factory->createClient('localhost:6380'),
    ];

    $command = function (Client $client) {
        return $client->incr('test');
    };

    var_dump(executeCommandOnAllClients($loop, $clients, $command));
// It is totally safe to execute the same command multiple times. Connections will be reused
    var_dump(executeCommandOnAllClients($loop, $clients, $command));
}

testExecuteCommandOnAllClients();
```

If you think the code is fine, I can send it to your examples in a PR.

**Comment by clue** [comment]
@halaei Happy to hear you've got this sorted and thank you for confirming back and providing this example code! I'm sure this is something many people looking for this will appreciate :+1:

I believe GitHub's search function will provide enough help to guide them to this ticket, so I don't think an additional example within this repo provides significantly more value.
